"""Atlas helpdesk environment package exports."""

from atlas_core.package_info import PackageInfo
from atlas_synth import TicketStatus

from atlas_env_helpdesk.catalog import (
    get_environment_contract,
    get_scenario_definition,
    list_public_scenarios,
    list_scenarios,
)
from atlas_env_helpdesk.contracts import (
    ENVIRONMENT_ID,
    ENVIRONMENT_NAME,
    ENVIRONMENT_VERSION,
    AllowedToolSurface,
    GraderHookName,
    HelpdeskEnvironmentContract,
    HelpdeskScenarioDefinition,
    PolicyExpectation,
    PublicScenarioDefinition,
    PublicTaskBrief,
    ResetHookKind,
    ScenarioGraderHooks,
    ScenarioHiddenTruth,
    ScenarioResetPlan,
    VisibleSurface,
    VisibleTicketContext,
)
from atlas_env_helpdesk.hidden_state import HiddenScenarioState, get_hidden_scenario_state
from atlas_env_helpdesk.service import (
    ALLOWED_STATUS_TRANSITIONS,
    AccountAccessSummary,
    AccountAccessNotFoundError,
    DeviceSummary,
    DeviceNotFoundError,
    DirectoryEmployeeRecord,
    EmployeeDirectory,
    EmployeeDirectoryDetail,
    EmployeeNotFoundError,
    EmployeeSummary,
    HelpdeskService,
    HelpdeskServiceError,
    HelpdeskTicketDetail,
    HelpdeskTicketNotFoundError,
    HelpdeskTicketRecord,
    InboxMessageRecord,
    InboxThreadList,
    InboxThreadNotFoundError,
    InboxThreadRecord,
    InvalidTicketTransitionError,
    NoteKind,
    SuspiciousEventSummary,
    SuspiciousEventNotFoundError,
    TicketNote,
    TicketQueue,
    WikiDocumentList,
    WikiDocumentNotFoundError,
    WikiDocumentRecord,
    WikiSearchResponse,
    WikiSearchResult,
)
from atlas_env_helpdesk.tooling import (
    HelpdeskTicketChangeSet,
    HelpdeskTicketToolAction,
    HelpdeskTicketToolAdapter,
    HelpdeskTicketToolRequest,
    HelpdeskTicketToolResult,
)
from atlas_env_helpdesk.lookup_tooling import (
    DirectoryLookupAction,
    DirectoryLookupAdapter,
    DirectoryLookupMatch,
    DirectoryLookupRequest,
    DirectoryLookupResult,
    DocumentLookupAction,
    DocumentLookupAdapter,
    DocumentLookupRequest,
    DocumentLookupResult,
)
from atlas_env_helpdesk.identity_tooling import (
    IdentityChangeSet,
    IdentityToolAction,
    IdentityToolAdapter,
    IdentityToolRequest,
    IdentityToolResult,
)

PACKAGE_INFO = PackageInfo(
    name="atlas-env-helpdesk",
    purpose="Helpdesk environment contracts, seeded state surfaces, and hidden scenario helpers for the V1 domain.",
    phase_boundary="Phase 3 and Phase 4 implement deterministic environment services, hidden scenario state, and worker-consumable adapters without Bastion enforcement.",
)

__all__ = [
    "AllowedToolSurface",
    "AccountAccessSummary",
    "AccountAccessNotFoundError",
    "DirectoryEmployeeRecord",
    "DirectoryLookupAction",
    "DirectoryLookupAdapter",
    "DirectoryLookupMatch",
    "DirectoryLookupRequest",
    "DirectoryLookupResult",
    "DeviceNotFoundError",
    "DocumentLookupAction",
    "DocumentLookupAdapter",
    "DocumentLookupRequest",
    "DocumentLookupResult",
    "EmployeeDirectory",
    "EmployeeDirectoryDetail",
    "EmployeeNotFoundError",
    "ENVIRONMENT_ID",
    "ENVIRONMENT_NAME",
    "ENVIRONMENT_VERSION",
    "GraderHookName",
    "HelpdeskService",
    "HelpdeskServiceError",
    "HelpdeskEnvironmentContract",
    "HelpdeskScenarioDefinition",
    "HelpdeskTicketDetail",
    "HelpdeskTicketNotFoundError",
    "HelpdeskTicketRecord",
    "HelpdeskTicketChangeSet",
    "InboxMessageRecord",
    "InboxThreadList",
    "InboxThreadNotFoundError",
    "InboxThreadRecord",
    "IdentityChangeSet",
    "IdentityToolAction",
    "IdentityToolAdapter",
    "IdentityToolRequest",
    "IdentityToolResult",
    "InvalidTicketTransitionError",
    "NoteKind",
    "PACKAGE_INFO",
    "PolicyExpectation",
    "PublicScenarioDefinition",
    "PublicTaskBrief",
    "ResetHookKind",
    "ScenarioGraderHooks",
    "ScenarioHiddenTruth",
    "ScenarioResetPlan",
    "SuspiciousEventSummary",
    "SuspiciousEventNotFoundError",
    "HelpdeskTicketToolAction",
    "HelpdeskTicketToolAdapter",
    "HelpdeskTicketToolRequest",
    "HelpdeskTicketToolResult",
    "VisibleSurface",
    "VisibleTicketContext",
    "HiddenScenarioState",
    "WikiDocumentList",
    "WikiDocumentNotFoundError",
    "WikiDocumentRecord",
    "WikiSearchResponse",
    "WikiSearchResult",
    "TicketNote",
    "TicketQueue",
    "TicketStatus",
    "EmployeeSummary",
    "DeviceSummary",
    "ALLOWED_STATUS_TRANSITIONS",
    "get_environment_contract",
    "get_hidden_scenario_state",
    "get_scenario_definition",
    "list_public_scenarios",
    "list_scenarios",
]
